@startuml
actor Kunde
actor Senior
actor Entwickler
== Initialisierung ==
Kunde -> Senior : Erteilung Auftrag Aufgabe 1
Senior -> Senior: Anlegen Issue "txt_to_md"
Senior -> Entwickler:  Zuweisen des Issues
== Implementierung ==
activate Senior
Senior -> Senior:  Beobachtung des Projekts
Entwickler -> Senior:  //Issue in progress//
activate Entwickler
Entwickler -> Entwickler:  Anlegen eines Branches
Entwickler -> Entwickler:  Implementieren 1
note right
 * Anlegen neue Datei
 * Kopieren der txt Inhalte
 * Formatieren als md
end note
Entwickler -> Entwickler:  Commiten
Entwickler -> Entwickler:  Implementieren 2
note right
 * Ergänzen eines Bildes
end note
Entwickler -> Entwickler:  Commiten
== Review ==
Entwickler -> Senior :  Pull request, Bitte um Review
Senior -> Entwickler :  Anforderung Nachbesserungen
note left
 * Einfügen eines Bildes
 * Rechtschreibkorrektur
end note
Entwickler -> Entwickler:  Implementieren 3
note right
 * Korrektur der Fehler
 * Einfügen einer Grafik
end note
Entwickler -> Senior :  Bitte um Rereview
Senior -> Entwickler :  Review abgeschlossen
deactivate Entwickler
== Deploy ==
Senior -> Senior:  Abschluss des Pullrequests
Senior -> Senior:  Generierung Release
deactivate Senior
@enduml
