@startuml
skinparam classAttributeIconSize 0
hide circle
hide Method
hide Field

class IEnumerator <T> <<interface>>
class IEnumerable <T> <<interface>>
class ICollection <T> <<interface>>
class IList <T>  <<interface>>
class IDictionary <K, V> <<interface>>

class List <T> #green
class Queue <T> #green
class Stack <T> #green
class LinkedList <T> #green
class Dictionary <K, V>  #green
class SortedList <K, V>  #green
class SortedDict <K, V>  #green

IEnumerable *-> IEnumerator
ICollection --> IEnumerable
IDictionary --> ICollection
IList --> ICollection

Dictionary ..|> IDictionary
SortedDict ..|> IDictionary
SortedList ..|> IDictionary
List ..|> IList
LinkedList ..|> IList
Queue ..|> ICollection
Stack ..|> ICollection
@enduml
