@startuml
skinparam classAttributeIconSize 0
hide circle

class Liste<T> {
  - T: head {T -> Person}
  + insert(T)
  + remove(T)
}

class PersonenListe<T> {
  + getbirthdayChild() : T

}

Liste <|-- PersonenListe

class Person <<abstract>>{
   name: string
   birthday: Date
   + getAgeInYears(): int
}

Person <|-- Mitarbeiter
Person <|-- Kunde
PersonenListe <|.. Kundenliste  : <<bind>>\n <T-> Kunde>
PersonenListe <|.. Mitarbeiterliste : <<bind>>\n <T-> Mitarbeiter>
@enduml
