@startuml
hide circle
interface SortierteListe <<Interface>>{
    einfuegen (Eintrag e);
    loeschen (Eintrag e);
}

class Datenbank {
  Object[] elementData
  size()
}

class Meßdaten {
  Object[] elementData
  size()
}

SortierteListe ()- Datenbank
SortierteListe ()- Meßdaten
@enduml
