@startuml
skinparam packageStyle rectangle
left to right direction
actor Distributor

rectangle Online-Shop {
  (Benutzernamen und Passwort eingeben) as USECASE1
  (Kunden- und Bestelldaten downloaden ) as USECASE2

  Distributor -- USECASE1
  Distributor -- USECASE2

  USECASE1 ..> (Zugriffsberechtigung prüfen) : <<include>>
  USECASE2 ..> (Daten im richtigen Format bereitstellen) : <<include>>

}
@enduml
