@startuml
left to right direction
skinparam packageStyle rectangle
actor Kunde

rectangle Onlineshop {
  (Artikel auswählen) as useCase1
  (Anschrift eingeben) as useCase2
  usecase ZAHLUNGSMETHODE as "Zahlungsmethode wählen.
  --
  Extention Points
  Bankeinzug"

  ZAHLUNGSMETHODE <.. (Daten für Bezahlung  eingeben) : <<extend>> \nCondition: {Bankeinzug gewählt}
  useCase2 ..> (Anschrift prüfen) :<<include>>

  Kunde -- useCase2
  Kunde -- (Bestellung absenden)
  Kunde -- useCase1
  Kunde -- ZAHLUNGSMETHODE

}
@enduml
