@startuml
|User|
start
repeat
:SchreibeDaten;
if (Speicher voll?) then (nein)
 :Ausgabe Speichergröße;
else (ja)
  |#AntiqueWhite|Admin|
  :Vergrößere Speicher;
  :Ausgabe zus. Speicher;
endif
|User|
:Speichern;
repeat while (Weitere Datensätze?)
stop
@enduml
