@startuml
participant Fahrer
participant Polizist
participant Akoholtester
participant Auto

Fahrer -> Polizist: Schlangenlinie fahren
activate Fahrer
activate Polizist

||15||
Polizist -> Fahrer: anhalten
activate Fahrer
Fahrer --> Polizist: anhalten:ok
deactivate Polizist
deactivate Fahrer
deactivate Fahrer

par
  Polizist -> Fahrer: Personalien prüfen
  activate Polizist
  activate Fahrer
  ||15||
  Fahrer --> Polizist: anhalten:ok
  deactivate Polizist
  deactivate Fahrer
else
  Polizist -> Auto: Fahrzeugzustand prüfen
  activate Polizist
  activate Auto
  Auto --> Polizist: Fahrzeug:ok
  deactivate Polizist
  deactivate Auto
end

alt Personalien != ok oder Fahrzeug != ok
  Polizist -> Fahrer: Austeigen lassen und mitnehmen
else
  Polizist -> Fahrer: Frage nach Alkohol
end

opt
  Polizist -> Akoholtester: Aktivieren
  activate Akoholtester
  ||10||
  Akoholtester -> Fahrer: Messung starten
  activate Fahrer
  ||10||
  Fahrer --> Akoholtester: Messung beendet:ok
  deactivate Fahrer
  ||5||
  Akoholtester -> Polizist: Ergebnis anzeigen
  deactivate Akoholtester
end
@enduml
