@startuml
skinparam classAttributeIconSize 0
class Example{
  attribute1: int
  + attribute2: int
  {static} public : double = 3.14
  - attribute3: boolean
  # attribute4: short
  ~ attribute5: String = "Test" {readonly}
  attribute6: B[0..1]{compoosite}
  attribute7: String [0..1]{ordered}
  / attribute8
}

class B{
  attribute9: int(attribut9 > 10)
}
@enduml
