@startuml
hide circle
abstract class AbstractList
abstract AbstractCollection
interface List <<Interface>>
interface Collection <<Interface>>

List <|.. AbstractList
Collection <|.. AbstractCollection

AbstractCollection <|-- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] elementData
  size()
}

@enduml
