@startuml
skinparam classAttributeIconSize 0
abstract class Car{
  - speed: double
  - numberOfSeats
  # setSpeed(double speed)
  + getSpeed() : double
}

class PassengerCar{
  - numberOfSeats: int = 5
}

class Bus{
  - numberOfSeats: int = 40
  + CheckTickets()
  + StopAtStation()
}

class TrafficOperator{
  - Vehicle: Car[]
  + superviseAllCars()
}

Car <|-- Bus : "erbt von"
Car <|-- PassengerCar : "erbt von"
TrafficOperator "1" -- "0:.. "PassengerCar : "greift zu auf"
TrafficOperator "1" -- "0:.. "Bus : "greift zu auf"
@enduml
