@startuml
skinparam classAttributeIconSize 0
hide circle
class Car{
  - speed: double
  - setSpeed(double speed)
  + GetSpeed() : double
}

class TrafficOperator{
  - Vehicles: Car[]
  + MonitorAllCars()
}

TrafficOperator "1" *-- "0:.. "Car : "greift zu auf"

note top of Car : speed als Property,\npublic get Methode, \nprivate set Methode
note top of TrafficOperator : Das Objekt kann auf die \nGeschwindigkeiten aller Fahrzeuge\n zurückgreifen, sie aber nicht verändern.
@enduml
