@startuml
left to right direction
skinparam packageStyle rectangle
actor Kunde
actor ShopManager
actor Lagerist
rectangle Onlineshop {
  (Artikel bestellen) as useCase1
   (Bestand durchsuchen) as useCase2
  Kunde -- useCase2
  Kunde -- (Kundendaten ändern)
  Kunde -- useCase1
  (Warenangebot pflegen) -- ShopManager
  (Bestellung zum Versand vorbereiten) -- Lagerist
}

rectangle "Banksystem für EC-Karten" as System2
System2 -- useCase1
rectangle "Online Bezahlsystem" as System3
System3 -- useCase1
@enduml
