@startuml
hide circle
skinparam classAttributeIconSize 0

class myStrings{
 + str_arr: string []
 + GetEnumerator(): IEnumerator<string>
 - IEnumerable.GetEnumerator(): IEnumerator
}

class StringEnumerator{
  - index: int
  - sp: myStrings
  + StringEnumerator (myStrings str_obj)
  - IEnumerator.Current(): object
  + Current(): string
}

interface IEnumerable<T> <<Interface>>{
  + GetEnumerator(): IEnumerator<T>
}

interface IEnumerable_ <<Interface>>{
  + GetEnumerator(): IEnumerator
}

interface IEnumerator_ <<Interface>>{
  + MoveNext(): bool
  + Reset(): void
  + Dispose(): void
}

interface IDisposable <<Interface>>{
  + Dispose(): void
}

interface IEnumerator<T> <<Interface>>{
  + Current: T
}

class Program {
  - spp: myStrings
  + {static}  Main(): void
}

Program --> myStrings
IEnumerable <|.. myStrings : <<bind>>\n <T-> string>
IEnumerable_ <|.. IEnumerable
IEnumerator <|.. StringEnumerator : <<bind>>\n <T-> string>
IEnumerator_ <|.. IEnumerator
IDisposable <|.. IEnumerator
myStrings <--> StringEnumerator
@enduml
